temp-directory: "./.nyc_output"
check-coverage: true
per-file: true
lines: 90
statements: 90
functions: 90
# branches: 90 ## TODO: This should be un-commented to 90 once code-coverage is improved!
all: true
include: [
  "src/**/*.js"
]
reporter: [
  "lcov"
]
exclude: [
  "src/setup.js",
  "src/lib/kafka/index.js",
  "**/node_modules/**"
]
